### ISSUE TITLE
Table ronde #7

### ISSUE THREAD

**Issue by revolunet** [putaindecode/tables-rondes#40]
Yo

C pas très "tech" mais je propose une table ronde sur les process/workflow de gestion de projet, depuis les specs jusqu'aux tests+mise en prod.

Quels outils/process pour améliorer la vie d'un projet, et celle des devs, entre les product owners, les devs, le design, les testeurs...

Chacun pourrait présenter son workflow actuel, ses pain-points et présenter des outils/solutions

ex:
 - outils pour les specs (API, UI, Stories...)
 - process de travail entre design/intégration/dev
 - gestion des tickets/milestones... agile ou pas

**Comment by kud** [comment]
Intéressant, je suis pour. Je comptais justement écrire un article à ce sujet.

**Comment by bloodyowl** [comment]
:+1:

**Comment by MattiSG** [comment]
OMG

http://mattischneider.fr/agile/outils
http://mattischneider.fr/anthropologie/agile/thesis

Yeah!

**Comment by revolunet** [comment]
@MattiSG : thanks :)

**Comment by revolunet** [comment]
ping @arnaudlimbourg

**Comment by arnaudlimbourg** [comment]
@revolunet pong (avec un joli lag). Sujet intéressant, c'est au final plus important que les outils.

**Comment by kud** [comment]
Cool @arnaudlimbourg

**Comment by risseraka** [comment]
Coucou

**Comment by kud** [comment]
Salut ça va ?

**Comment by MattiSG** [comment]
Le resto était bien.

**Comment by risseraka** [comment]
Imhothep. : p

**Comment by bobylito** [comment]
Yo ça a l'air intéressant même si je suis plutôt un brin anarchiste dans le domaine ;P

**Comment by bobylito** [comment]
Ça devrait pouvoir s'héberger chez Algolia si vous voulez.

**Comment by arnaudlimbourg** [comment]
@bobylito cool !

Le doodle de circonstance http://doodle.com/amqmwqr3t6c27cvi

**Comment by bobylito** [comment]
Hello tout le monde a voté? Le 20 ça vous va toujours, car ça parait bon pour cette date du coté de chez Algolia :).

Une question cependant, ça vous va si on en parle d'une manière ou d'une autre dans la comm' d'Algolia?

**Comment by kud** [comment]
Tu souhaites parler d'Algolia durant la table ronde ?

**Comment by bloodyowl** [comment]
@bobylito pas de souci pour moi, juste pas d'annonce avant d'event histoire de pas rameuter du monde pas inscrit ici :)

**Comment by bobylito** [comment]
@kud Oh non pas vraiment, c'est juste que je crois que l'on souhaiterait dire que l'on host ou un truc comme ça. C'est pas super clair non plus ;)

**Comment by kud** [comment]
Pour ma part, je pense qu'une table ronde n'est pas un meetup ou une conférence; c'est plus un bar à discussion entre potes dev. Du coup, le sponsoring ou je ne sais quoi en intro me semble mal vu.

Après on apprécie totalement être hébergés quelque part, et j'ai aucun souci à ce qu'une personne qui travaille dans la boite présente aussi sa boite durant la présentation de chacun. Mais je pense que si Algolia veut présenter son truc, qu'elle le fasse pour les intéressés juste après la discussion.

Encore une fois, ca reste que mon opinion, mais les 5-10min de prez de la société qui héberge quand je vais dans un meetup; perso ça m'emmerde plus qu'autre chose.

**Comment by bobylito** [comment]
@kud : deux choses, d'une part c'est pas ce que je voulais dire, je vais pas présenter Algolia. Je crois qu'ils veulent en parler à l'extérieur, twitter ou whatever. Et d'autre part, je suis d'accord avec toi, c'est pas un meetup, c'est pas le même esprit.

Après bon si ya des curieux qui connaissent pas Algolia, je serais heureux de répondre aux questions, mais c'est clairement pas le but (ou en tout cas pas pour moi)

**Comment by kud** [comment]
Comme ce n'était pas clair, j'ai préféré préciser ce que je ne souhaite pas. ;)

Si c'est juste un tweet ou du style; y'a aucun problème pour moi aussi, évident. Après comme dit @bloodyowl; évitons de le mettre trop tôt pour ramener mass monde.

**Comment by bobylito** [comment]
Works for me. C'est bien aussi de dire ce que l'on en pense comme ça ce sera plus clair pour les prochaines fois.

**Comment by MattiSG** [comment]
Mes 0,02€ : associer une boîte à une table ronde jusqu'ici plutôt confidentielle (c'est le ressenti de personnes extérieures à P!), sur laquelle aucune entité autre que P! a communiqué (et encore, même là, pas des masses), c'est un petit risque de com’ pour une organisation pas hyper lisible (penser : « ah ok P! c'est Algolia en fait »).

**Comment by arnaudlimbourg** [comment]
Doodle fermé, mis au 20 mai. Merci à Algolia :)

**Comment by bobylito** [comment]
Ouais en fait yavait une incompréhension ici ;) Du coup, pas de plan de comm' et c'est bien compris que c'est informel. Pas de problèmes d'association involontaire ;)

**Comment by bloodyowl** [comment]
hop, c'est parti pour s'inscrire par PR https://github.com/putaindecode/tables-rondes/blob/master/7.md

**Comment by risseraka** [comment]
J'veux venir mais j'suis timide et j'ai rien à dire. Une prochaine fois peut-être ? : (

**Comment by bloodyowl** [comment]
beh viens pour écouter dans ce cas :smile:

**Comment by risseraka** [comment]
Ça sera une table trapézoïdale alors...  ; )
Je m'inscris !

**Comment by risseraka** [comment]
Salut les petits clous,
Désolé de vous faire ça mais je vais devoir annuler ma présence, je me suis engagé pour donner un talk au meetup Node.js le même jour.
Je me permets car n'ayant pas grand chose à partager je comptais venir en tant que spectateur.
Désolé et à la prochaine !
Bisoux

**Comment by MoOx** [comment]
Vous tentez d'enregistrer votre table ronde ? (audio only ?)

**Comment by MoOx** [comment]
Qu'on fasse un podcast :)

**Comment by MattiSG** [comment]
@MoOx Mince, je crois pas que quelqu'un y ait pensé…

**Comment by MoOx** [comment]
Les non réponses m'avaient bien prédit cela :)

**Comment by MattiSG** [comment]
La présentation qu'on a réussi à aller à la moitié  ;)  : https://speakerdeck.com/mattisg/agile-cest-quoi
La référence supplémentaire à la fin sur la [combinaison d'outils](https://www.youtube.com/watch?v=FtJVsgOWT4w) : https://speakerdeck.com/mattisg/choisir-son-outil-de-gestion-de-projet-agile?slide=39.

Et enfin, en cadeau pour @bloodyowl qui s'est bien foutu de moi (m'en fous, j'ai gagné la première manche et la deuxième a été interrompue par le gong) : [Evidence Based Scheduling](http://www.joelonsoftware.com/items/2007/10/26.html).
Morceau choisi :

> When these teams ship, two years late, that weird guy with the file cabinet in his office brings the old printout to the post mortem, and everyone has a good laugh. “Hey look! We allowed two weeks for rewriting from scratch in Ruby!”
>
> Hilarious! If you’re still in business.

**Comment by MattiSG** [comment]
Pour @Freddy03h (découpage des stories) :

- [INVEST](http://en.wikipedia.org/wiki/INVEST_(mnemonic))
- [Elephant Carpaccio](http://alistair.cockburn.us/Elephant+Carpaccio+Exercise)
- [Cheat sheet](http://www.agileforall.com/wp-content/uploads/2009/10/Story-Splitting-Cheat-Sheet.pdf)
- [Diagramme décisionnel](http://www.agileforall.com/wp-content/uploads/2012/01/Story-Splitting-Flowchart.pdf)

**Comment by revolunet** [comment]
si kk'un est motivé pour faire un micro-recap :)

**Comment by dlamoureux** [comment]
Merci pour toutes ces sources d'information et pour cette table très enrichissante.

**Comment by MattiSG** [comment]
> si kk'un est motivé pour faire un micro-recap :)

### Acte 1

Tous : Scrum et agile c'est de la merde.
@kud : j'ai fait pas mal d'environnements divers, et encore faudrait-il savoir ce qu'est vraiment Scrum. _Il explique._
Tous : lol.

### Acte 2

_@MattiSG fulmine._ https://speakerdeck.com/mattisg/agile-cest-quoi
@bloodyowl : lol. Peut-être mais pour 99% des gens c'est pas ça. Et puis j'aime bien la documentation exhaustive.
@arnaudlimbourg : les valeurs sont à comprendre dans un contexte de ressources finies.
@bloodyowl : _mauvaise foi_.
@dlamoureux : tell me more about agile.

### Acte 3

@skinnyfoetusboy : mais @MattiSG je comprends pas, pourquoi à la F**C c'était du gros caca alors qu'ils disaient que c'était agile ?
@MattiSG : viens, je vais t'expliquer. C'est des cons.
@skinnyfoetusboy : _fait des comparaisons étranges avec le communisme et Staline_.
@Freddy03h : mais pourquoi chez nous c'est du gros caca alors qu'ils disent que c'est agile ?

_Un autre groupe se forme autour de @kud._

### Acte 4

@bloodyowl, _qui fomentait sa vengeance depuis une heure_ : ouais mais les estimations c'est inutile.
@remitbri : ben des fois t'es un peu obligé de donner une date, quand même. Même approximative. Un peu.
@bloodyowl : _défend la stratégie Duke Nukem 3D_.
Quelqu'un : bon, on va manger un burger ?

**Ils sortent. Le rire sauvage de @bloodyowl s'éloigne dans la nuit.**

**Comment by bloodyowl** [comment]
lel

**Comment by revolunet** [comment]
haha :)

**Comment by risseraka** [comment]
Comme si on y était, génial !

**Comment by skinnyfoetusboy** [comment]
>la stratégie Duke Nukem 3D
oi m8
wot

**Comment by arnaudlimbourg** [comment]
J'adore le résumé :)

**Comment by kud** [comment]
Ce serait bien la prochaine fois d'éviter de couper la parole tout de même, et d'avancer correctement.

**Comment by MattiSG** [comment]
Bâton de parole et @kud frappe ceux qui ne respectent pas.
